on: push
name: dotnet
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@GitHub-Actions
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.202
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test --configuration Release --no-build
    - name: Publish with dotnet
      run: dotnet publish --configuration Release --no-build
    