# This workflow will build and push a Docker container to Docker Hub
name: ci
on:
  push:
    branches: [Github-Actions]
    tags:
      - "*.*.*"
jobs:
  build:
    name: Build, Test and Push Docker image.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout.
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.202
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
  docker:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - name: Checkout.
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        working-directory: ./WebAPI/
        run: dotnet publish -c Release
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/webapijwt --all-tags
